name: nginx-ingress-controller
version: 0.18.0
appVersion: 0.0.1
description: Chart for the nginx Ingress controller
keywords:
- ingress
- nginx
- http
- web
- www
- reverse proxy
home: http://www.nginx.org
sources:
- https://github.com/bitnami/bitnami-docker-nginx-ingress-controller
maintainers:
- name: Bitnami
  email: containers@bitnami.com
engine: gotpl
